dual gap limit
Wikunia/Bonobo.jl pull request #39
Opened 2022-07-21 09:49 UTC by matbesancon

termination should be checked with a duality gap of the whole tree instead of empty nodes.

2022-07-21 10:13 UTC, Wikunia requested changes

2022-07-21 10:13 UTC, Wikunia commented on src/Bonobo.jl
> +    dual_gap = tree.incumbent - tree.lb
Isn't it normally computed as a percentage?

2022-07-21 10:13 UTC, Wikunia commented on src/Bonobo.jl
>  Default behavior is to terminate the loop only when no nodes exist in the priority queue.
would need to update the docstring here

2022-07-21 10:17 UTC, matbesancon commented on src/Bonobo.jl
> +    dual_gap = tree.incumbent - tree.lb
you're right there are both, in SCIP:
```
# solving stops, if the relative gap = |primal - dual|/MIN(|dual|,|primal|) is below the given value, the gap is 'Infinity', if primal and dual bound have opposite signs
# [type: real, advanced: FALSE, range: [0,1.79769313486232e+308], default: 0]
limits/gap = 0

# solving stops, if the absolute gap = |primalbound - dualbound| is below the given value
# [type: real, advanced: FALSE, range: [0,1.79769313486232e+308], default: 0]
limits/absgap = 0
```

2022-07-21 10:23 UTC, matbesancon commented on src/Bonobo.jl
> +    dual_gap = tree.incumbent - tree.lb
fixed in last commit

2022-07-21 10:25 UTC, matbesancon commented on src/Bonobo.jl
>  Default behavior is to terminate the loop only when no nodes exist in the priority queue.
done

2022-07-21 10:32 UTC, matbesancon commented
Now that I think of it, let's also add absolute gap

2022-07-21 13:15 UTC, matbesancon commented on src/Bonobo.jl
> +    absgap = tree.incumbent - tree.lb
yes I assumed minimization here, in which case yup this is always in the same sense

2022-07-21 15:41 UTC, matbesancon commented
all good on the comments it seems?

2022-07-21 18:38 UTC, Wikunia commented
Looks good maybe would be nice to have some easy tests for this.

2022-07-23 07:53 UTC, matbesancon commented
I added a simple test although the gap will only show up for large enough problems.

There was also a bug in a condition that was checking `:sense == :Max` instead of `sense == :Max`

2022-07-23 09:12 UTC, Wikunia commented
Great thanks. Do you mind adding a line to the changelog then I'm happy to merge.

2022-07-26 10:51 UTC, matbesancon commented
done!

2022-07-27 17:15 UTC, merged